name: nemo_search
channels:
  - conda-forge
  - defaults
dependencies:
  - black=24.8.0=py39hca03da5_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py39hbda83bc_0
  - brotli=1.1.0=hb547adb_1
  - brotli-bin=1.1.0=hb547adb_1
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2024.12.31=hca03da5_0
  - celluloid=0.2.0=pyhd8ed1ab_0
  - certifi=2024.12.14=py39hca03da5_0
  - click=8.1.7=py39hca03da5_0
  - contourpy=1.3.0=py39h85b62ae_2
  - cycler=0.12.1=pyhd8ed1ab_0
  - et_xmlfile=1.1.0=py39hca03da5_0
  - ffmpeg=4.2.2=h04105a8_0
  - fonttools=4.51.0=py39h80987f9_0
  - freetype=2.12.1=h1192e45_0
  - gettext=0.21.0=hbdbcc25_2
  - gmp=6.2.1=hc377ac9_3
  - gnutls=3.6.15=h887c41c_0
  - h5py=3.12.1=py39h0957e0b_1
  - hdf5=1.14.5=h575951c_0
  - icu=73.1=h313beb8_0
  - importlib-resources=6.4.0=pyhd3eb1b0_0
  - importlib_resources=6.4.0=py39hca03da5_0
  - jinja2=3.1.5=py39hca03da5_0
  - joblib=1.4.2=py39hca03da5_0
  - kiwisolver=1.4.5=py39hbd775c9_1
  - krb5=1.20.1=hf3e1bf2_1
  - lame=3.100=h1a28f6b_0
  - lcms2=2.16=ha0e7c42_0
  - lerc=4.0.0=h313beb8_0
  - libblas=3.9.0=1_h2ec9a88_netlib
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=1_h9886b1c_netlib
  - libcurl=8.11.1=hde089ae_0
  - libcxx=19.1.6=ha82da77_1
  - libdeflate=1.19=hb547adb_0
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libiconv=1.16=h80987f9_3
  - libidn2=2.3.4=h80987f9_0
  - libjpeg-turbo=3.0.3=h80987f9_0
  - liblapack=3.9.0=1_h9886b1c_netlib
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.21=h269037a_0
  - libopus=1.3.1=h80987f9_1
  - libpng=1.6.43=h091b4b1_0
  - libsqlite=3.46.0=hfb93653_0
  - libssh2=1.11.1=h3e2b118_0
  - libtasn1=4.19.0=h80987f9_0
  - libtiff=4.6.0=ha8a6c65_2
  - libunistring=0.9.10=h1a28f6b_0
  - libvpx=1.10.0=hc377ac9_0
  - libwebp-base=1.3.2=h80987f9_1
  - libxcb=1.15=hf346824_0
  - libxml2=2.13.5=h0b34f26_0
  - libzlib=1.2.13=hfb2fe0b_6
  - llvm-openmp=17.0.6=hcd81f8e_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=2.1.3=py39h80987f9_1
  - matplotlib-base=3.9.2=py39h7ef442a_1
  - munkres=1.1.4=py_0
  - mypy_extensions=1.0.0=py39hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nettle=3.7.3=h84b5d62_1
  - numexpr=2.10.1=py39h5d9532f_0
  - numpy=2.0.1=py39h3b2db8e_1
  - numpy-base=2.0.1=py39ha9811e2_1
  - openh264=1.8.0=h98b2900_0
  - openjpeg=2.5.2=h54b8e55_0
  - openpyxl=3.1.5=py39h80987f9_0
  - openssl=3.2.1=h0d3ecfb_0
  - packaging=24.2=py39hca03da5_0
  - pandas=2.2.3=py39hcf29cfe_0
  - pathspec=0.10.3=py39hca03da5_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pillow=10.3.0=py39h3352c98_0
  - pip=24.2=py39hca03da5_0
  - platformdirs=3.10.0=py39hca03da5_0
  - pthread-stubs=0.4=h27ca646_1001
  - pybind11-abi=4=hd3eb1b0_1
  - pyparsing=3.2.0=py39hca03da5_0
  - python=3.9.12=h14b404e_1_cpython
  - python-dateutil=2.9.0post0=py39hca03da5_2
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.9=5_cp39
  - pytz=2024.1=py39hca03da5_0
  - readline=8.2=h1a28f6b_0
  - scikit-learn=1.5.2=py39h313beb8_0
  - scipy=1.13.1=py39hd336fd7_1
  - seaborn=0.13.2=hd8ed1ab_0
  - seaborn-base=0.13.2=pyhd8ed1ab_0
  - setuptools=75.1.0=py39hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h80987f9_0
  - statsmodels=0.14.4=py39h80987f9_0
  - threadpoolctl=3.5.0=py39h33ce5c2_0
  - tk=8.6.14=h6ba3021_0
  - tomli=2.0.1=py39hca03da5_0
  - tqdm=4.66.5=py39h33ce5c2_0
  - typing_extensions=4.12.2=py39hca03da5_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py39h80987f9_0
  - wheel=0.44.0=py39hca03da5_0
  - x264=1!152.20180806=h1a28f6b_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.4.6=h80987f9_1
  - zipp=3.21.0=py39hca03da5_0
  - zlib=1.2.13=hfb2fe0b_6
  - zstd=1.5.6=hfb09047_0
  - pip:
      - i2mc==2.2.4
      - opencv-python==4.11.0.86
prefix: /Users/4137477/anaconda3/envs/nemo_search
